---
openapi: '3.0.0'
info:
  title: 'Ternurines API'
  version: '1.0.0'
  description: 'API de los personajes de la franquicia Sylvanian Families'
servers:
  - url: "http://localhost:3000"
tags:
  name: Characters
  description: Sylvanian Families' characters.
components:
  schemas:
    Character:
      type: object
      properties:
        name:
          type: string
          description: Character's name.
        family:
          type: string
          description: Family that the character belongs to.
        role:
          type: string
          description: The role the character has in the family.
        description:
          type: string
          description: Some description about the character.
        image:
          type: string
          description: Image URL of the character.
paths:
  /characters/{characterId}:
    get:
      tags:
        - Characters
      summary: Find character by ID
      description: Returns a single characters
      parameters:
        - name: characterId
          in: path
          description: ID of character to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:          
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
        '400':
          description: Invalid ID supplied
        '404':
          description: Character not found